# Generated by Django 4.2 on 2024-08-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
